// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gmail.volodymyrdotsenko.qr.domain;

import com.gmail.volodymyrdotsenko.qr.domain.UserData;
import java.io.Serializable;

privileged aspect UserData_Roo_Serializable {
    
    declare parents: UserData implements Serializable;
    
    private static final long UserData.serialVersionUID = 1L;
    
}
