// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.gmail.volodymyrdotsenko.qr.domain;

import com.gmail.volodymyrdotsenko.qr.domain.UserToken;
import java.io.Serializable;

privileged aspect UserToken_Roo_Serializable {
    
    declare parents: UserToken implements Serializable;
    
    private static final long UserToken.serialVersionUID = 1L;
    
}
